### ISSUE TITLE
An error when MUSIC/src/evolve.cpp runs at line 211.

### ISSUE THREAD

**Issue by kaisershafi** [MUSIC-fluid/MUSIC#7]
Hi! 
What is the meaning of  the following error in
MUSIC/src/evolve.cpp, line 211?
**"The maximum energy density increased by
more than facotor of 2! This should not happen"**
The evolution runs for 8-10 fm and then stops
because of the error. I was doing e-by-e hydro
using MUSIC, this error occurs with majority of
the ICs that I've generated.

Thanks a lot.

**Comment by kaisershafi** [comment]
[ic_to_music.zip](https://github.com/MUSIC-fluid/MUSIC/files/13702738/ic_to_music.zip)
Here is the IC.

**Comment by chunshen1987** [comment]
Hi,

Your runtime error is caused by numerical instability when the viscous part of the energy-momentum tensor becomes too large compared to the ideal component. You can set `quest_revert_strength` to 1 in your input file to increase the numerical stability.  

Chun

**Comment by kaisershafi** [comment]
Thanks a lot for your response.
I'll try that.
